<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>CampusHub Activity Report</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; margin: 0; padding: 0; }
    .header { background: #4f46e5; color: white; padding: 24px 32px; margin-bottom: 24px; }
    .header h1 { margin: 0 0 4px 0; font-size: 22px; }
    .header p { margin: 0; opacity: 0.85; font-size: 11px; }
    .section { padding: 0 32px 20px; }
    .section h2 { font-size: 14px; color: #4f46e5; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin-bottom: 12px; }
    .stats-grid { display: table; width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    .stat-box { display: table-cell; width: 25%; background: #f9fafb; border: 1px solid #e5e7eb; padding: 12px; text-align: center; }
    .stat-box .value { font-size: 22px; font-weight: bold; color: #4f46e5; }
    .stat-box .label { font-size: 10px; color: #6b7280; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { background: #f3f4f6; text-align: left; padding: 8px 10px; font-size: 10px; text-transform: uppercase; color: #6b7280; }
    td { padding: 8px 10px; border-bottom: 1px solid #f3f4f6; }
    tr:nth-child(even) td { background: #fafafa; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 20px; font-size: 10px; font-weight: bold; }
    .badge-pending { background: #fef3c7; color: #d97706; }
    .badge-completed { background: #d1fae5; color: #059669; }
    .badge-in_progress { background: #dbeafe; color: #2563eb; }
    .badge-cancelled { background: #f3f4f6; color: #6b7280; }
    .footer { margin-top: 32px; padding: 16px 32px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>

<div class="header">
    <h1>CampusHub Activity Report</h1>
    <p>Generated: {{ now()->format('F j, Y \a\t g:i A') }} &nbsp;|&nbsp; Period: {{ $period }}</p>
</div>

<div class="section">
    <h2>Summary Statistics</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="value">{{ $stats['total_requests'] }}</div>
            <div class="label">Total Requests</div>
        </div>
        <div class="stat-box">
            <div class="value">{{ $stats['completed'] }}</div>
            <div class="label">Completed</div>
        </div>
        <div class="stat-box">
            <div class="value">{{ $stats['active_providers'] }}</div>
            <div class="label">Active Providers</div>
        </div>
        <div class="stat-box">
            <div class="value">₵{{ number_format($stats['revenue'], 2) }}</div>
            <div class="label">Revenue</div>
        </div>
    </div>
</div>

<div class="section">
    <h2>Recent Service Requests</h2>
    <table>
        <thead>
            <tr>
                <th>Request #</th>
                <th>Title</th>
                <th>Student</th>
                <th>Service</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($requests as $req)
            <tr>
                <td>{{ $req->request_number }}</td>
                <td>{{ Str::limit($req->title, 40) }}</td>
                <td>{{ $req->student?->name }}</td>
                <td>{{ $req->service?->name }}</td>
                <td><span class="badge badge-{{ $req->status }}">{{ str_replace('_', ' ', ucfirst($req->status)) }}</span></td>
                <td>{{ $req->created_at->format('M j, Y') }}</td>
            </tr>
            @empty
            <tr><td colspan="6" style="text-align:center;color:#9ca3af;">No requests in this period.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>

<div class="footer">
    This report was automatically generated by CampusHub &mdash; Smart Campus Service Platform &copy; {{ date('Y') }}
</div>

</body>
</html>
